# Example prometheus agent configuration for collecting metrics from the exporter and forwarding to cortex
remote_write:
  - url: http://cortex.k3d.localhost:50080/api/prom/push
global:
  scrape_interval: 1m

scrape_configs:
  - job_name: "vmware_exporter"
    static_configs:
      - targets: ["localhost:9237"]
